server:
  port: 2443
  ssl:
    enabled: true
    client-auth: need
    key-store: file:${KEYSTORE}
    key-store-password: ${KEYSTORE_PASSWD}
    trust-store: file:${TRUSTSTORE}
    trust-store-password: ${TRUSTSTORE_PASSWD}

clamp:
  url: https://policy-clamp-be:8443
  disable-ssl-validation: false
  disable-ssl-hostname-check: true

apex-editor:
  upload-url:
  upload-userid:

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus
